version: "3.9"

networks:
  internal:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: "${APP_NAME}-server"
    hostname: "${APP_NAME}"
    ports:
      - "${APP_PORT}:80"
    working_dir: /var/www/html
    environment:
      - "DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5"
    volumes:
      - www:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    develop:
      watch:
        - action: sync
          path: ./www
          target: /var/www/html
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - internal

  db_server:
    image: mariadb:10.5.9
    container_name: "${APP_NAME}-db"
    hostname: "${APP_NAME}-db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/docker.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - internal

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "${APP_NAME}-mssql"
    hostname: "${APP_NAME}-mssql"

    ports:
      - ${MSSQL_PORT}:1433
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASS}
    networks:
      - internal

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: "${APP_NAME}-myadmin"
    ports:
      - "${APP_DB_ADMIN_PORT}:80"
    environment:
      PMA_HOST: db_server
      UPLOAD_LIMIT: 300M
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - internal

volumes:
  www:
  db_data:
  mssql_data:
